//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prodma.DataAccessB2C.ozceteFiyatlar {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfErp_siparis", Namespace="http://tempuri.org/", ItemName="erp_siparis")]
    [System.SerializableAttribute()]
    public class ArrayOfErp_siparis : System.Collections.Generic.List<Prodma.DataAccessB2C.ozceteFiyatlar.erp_siparis> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="erp_siparis", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class erp_siparis : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stok_koduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tedarikciField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string miktarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string stok_kodu {
            get {
                return this.stok_koduField;
            }
            set {
                if ((object.ReferenceEquals(this.stok_koduField, value) != true)) {
                    this.stok_koduField = value;
                    this.RaisePropertyChanged("stok_kodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string tedarikci {
            get {
                return this.tedarikciField;
            }
            set {
                if ((object.ReferenceEquals(this.tedarikciField, value) != true)) {
                    this.tedarikciField = value;
                    this.RaisePropertyChanged("tedarikci");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string miktar {
            get {
                return this.miktarField;
            }
            set {
                if ((object.ReferenceEquals(this.miktarField, value) != true)) {
                    this.miktarField = value;
                    this.RaisePropertyChanged("miktar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ozceteFiyatlar.OzceteParcaSatisSoap")]
    public interface OzceteParcaSatisSoap {
        
        // CODEGEN: Generating message contract since element name list from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fn_siparis_olustur", ReplyAction="*")]
        Prodma.DataAccessB2C.ozceteFiyatlar.fn_siparis_olusturResponse fn_siparis_olustur(Prodma.DataAccessB2C.ozceteFiyatlar.fn_siparis_olusturRequest request);
        
        // CODEGEN: Generating message contract since element name d_stok_kodu from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fn_stok_listesi", ReplyAction="*")]
        Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_listesiResponse fn_stok_listesi(Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_listesiRequest request);
        
        // CODEGEN: Generating message contract since element name d_sifre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fn_stok_kampanyali_stoklar", ReplyAction="*")]
        Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_kampanyali_stoklarResponse fn_stok_kampanyali_stoklar(Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_kampanyali_stoklarRequest request);
        
        // CODEGEN: Generating message contract since element name d_stok_kodu from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fn_stok_durumu", ReplyAction="*")]
        Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_durumuResponse fn_stok_durumu(Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_durumuRequest request);
        
        // CODEGEN: Generating message contract since element name d_sifre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fn_stok_bakiye_listesi", ReplyAction="*")]
        Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_bakiye_listesiResponse fn_stok_bakiye_listesi(Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_bakiye_listesiRequest request);
        
        // CODEGEN: Generating message contract since element name d_sifre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fn_cari_hareket", ReplyAction="*")]
        Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareketResponse fn_cari_hareket(Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareketRequest request);
        
        // CODEGEN: Generating message contract since element name d_siparis from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fn_cari_hareket_detay", ReplyAction="*")]
        Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareket_detayResponse fn_cari_hareket_detay(Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareket_detayRequest request);
        
        // CODEGEN: Generating message contract since element name d_siparis_no from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fn_cari_hareket_siparis_no", ReplyAction="*")]
        Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareket_siparis_noResponse fn_cari_hareket_siparis_no(Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareket_siparis_noRequest request);
        
        // CODEGEN: Generating message contract since element name d_sifre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fn_siparis_erp_no", ReplyAction="*")]
        Prodma.DataAccessB2C.ozceteFiyatlar.fn_siparis_erp_noResponse fn_siparis_erp_no(Prodma.DataAccessB2C.ozceteFiyatlar.fn_siparis_erp_noRequest request);
        
        // CODEGEN: Generating message contract since element name d_siparis_no from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fn_stok_bakiye_iptal", ReplyAction="*")]
        Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_bakiye_iptalResponse fn_stok_bakiye_iptal(Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_bakiye_iptalRequest request);
        
        // CODEGEN: Generating message contract since element name d_sifre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fn_kur", ReplyAction="*")]
        Prodma.DataAccessB2C.ozceteFiyatlar.fn_kurResponse fn_kur(Prodma.DataAccessB2C.ozceteFiyatlar.fn_kurRequest request);
        
        // CODEGEN: Generating message contract since element name d_deger from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fn_web_sifre_olustur", ReplyAction="*")]
        Prodma.DataAccessB2C.ozceteFiyatlar.fn_web_sifre_olusturResponse fn_web_sifre_olustur(Prodma.DataAccessB2C.ozceteFiyatlar.fn_web_sifre_olusturRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fn_siparis_olusturRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fn_siparis_olustur", Namespace="http://tempuri.org/", Order=0)]
        public Prodma.DataAccessB2C.ozceteFiyatlar.fn_siparis_olusturRequestBody Body;
        
        public fn_siparis_olusturRequest() {
        }
        
        public fn_siparis_olusturRequest(Prodma.DataAccessB2C.ozceteFiyatlar.fn_siparis_olusturRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fn_siparis_olusturRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Prodma.DataAccessB2C.ozceteFiyatlar.ArrayOfErp_siparis list;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string d_sifre;
        
        public fn_siparis_olusturRequestBody() {
        }
        
        public fn_siparis_olusturRequestBody(Prodma.DataAccessB2C.ozceteFiyatlar.ArrayOfErp_siparis list, string d_sifre) {
            this.list = list;
            this.d_sifre = d_sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fn_siparis_olusturResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fn_siparis_olusturResponse", Namespace="http://tempuri.org/", Order=0)]
        public Prodma.DataAccessB2C.ozceteFiyatlar.fn_siparis_olusturResponseBody Body;
        
        public fn_siparis_olusturResponse() {
        }
        
        public fn_siparis_olusturResponse(Prodma.DataAccessB2C.ozceteFiyatlar.fn_siparis_olusturResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fn_siparis_olusturResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fn_siparis_olusturResult;
        
        public fn_siparis_olusturResponseBody() {
        }
        
        public fn_siparis_olusturResponseBody(string fn_siparis_olusturResult) {
            this.fn_siparis_olusturResult = fn_siparis_olusturResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fn_stok_listesiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fn_stok_listesi", Namespace="http://tempuri.org/", Order=0)]
        public Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_listesiRequestBody Body;
        
        public fn_stok_listesiRequest() {
        }
        
        public fn_stok_listesiRequest(Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_listesiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fn_stok_listesiRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string d_stok_kodu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string d_tedarikci;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double d_miktar;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string d_sifre;
        
        public fn_stok_listesiRequestBody() {
        }
        
        public fn_stok_listesiRequestBody(string d_stok_kodu, string d_tedarikci, double d_miktar, string d_sifre) {
            this.d_stok_kodu = d_stok_kodu;
            this.d_tedarikci = d_tedarikci;
            this.d_miktar = d_miktar;
            this.d_sifre = d_sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fn_stok_listesiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fn_stok_listesiResponse", Namespace="http://tempuri.org/", Order=0)]
        public Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_listesiResponseBody Body;
        
        public fn_stok_listesiResponse() {
        }
        
        public fn_stok_listesiResponse(Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_listesiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fn_stok_listesiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fn_stok_listesiResult;
        
        public fn_stok_listesiResponseBody() {
        }
        
        public fn_stok_listesiResponseBody(string fn_stok_listesiResult) {
            this.fn_stok_listesiResult = fn_stok_listesiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fn_stok_kampanyali_stoklarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fn_stok_kampanyali_stoklar", Namespace="http://tempuri.org/", Order=0)]
        public Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_kampanyali_stoklarRequestBody Body;
        
        public fn_stok_kampanyali_stoklarRequest() {
        }
        
        public fn_stok_kampanyali_stoklarRequest(Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_kampanyali_stoklarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fn_stok_kampanyali_stoklarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string d_sifre;
        
        public fn_stok_kampanyali_stoklarRequestBody() {
        }
        
        public fn_stok_kampanyali_stoklarRequestBody(string d_sifre) {
            this.d_sifre = d_sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fn_stok_kampanyali_stoklarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fn_stok_kampanyali_stoklarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_kampanyali_stoklarResponseBody Body;
        
        public fn_stok_kampanyali_stoklarResponse() {
        }
        
        public fn_stok_kampanyali_stoklarResponse(Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_kampanyali_stoklarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fn_stok_kampanyali_stoklarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fn_stok_kampanyali_stoklarResult;
        
        public fn_stok_kampanyali_stoklarResponseBody() {
        }
        
        public fn_stok_kampanyali_stoklarResponseBody(string fn_stok_kampanyali_stoklarResult) {
            this.fn_stok_kampanyali_stoklarResult = fn_stok_kampanyali_stoklarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fn_stok_durumuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fn_stok_durumu", Namespace="http://tempuri.org/", Order=0)]
        public Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_durumuRequestBody Body;
        
        public fn_stok_durumuRequest() {
        }
        
        public fn_stok_durumuRequest(Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_durumuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fn_stok_durumuRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string d_stok_kodu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string d_tedarikci;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string d_sifre;
        
        public fn_stok_durumuRequestBody() {
        }
        
        public fn_stok_durumuRequestBody(string d_stok_kodu, string d_tedarikci, string d_sifre) {
            this.d_stok_kodu = d_stok_kodu;
            this.d_tedarikci = d_tedarikci;
            this.d_sifre = d_sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fn_stok_durumuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fn_stok_durumuResponse", Namespace="http://tempuri.org/", Order=0)]
        public Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_durumuResponseBody Body;
        
        public fn_stok_durumuResponse() {
        }
        
        public fn_stok_durumuResponse(Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_durumuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fn_stok_durumuResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fn_stok_durumuResult;
        
        public fn_stok_durumuResponseBody() {
        }
        
        public fn_stok_durumuResponseBody(string fn_stok_durumuResult) {
            this.fn_stok_durumuResult = fn_stok_durumuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fn_stok_bakiye_listesiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fn_stok_bakiye_listesi", Namespace="http://tempuri.org/", Order=0)]
        public Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_bakiye_listesiRequestBody Body;
        
        public fn_stok_bakiye_listesiRequest() {
        }
        
        public fn_stok_bakiye_listesiRequest(Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_bakiye_listesiRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fn_stok_bakiye_listesiRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string d_sifre;
        
        public fn_stok_bakiye_listesiRequestBody() {
        }
        
        public fn_stok_bakiye_listesiRequestBody(string d_sifre) {
            this.d_sifre = d_sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fn_stok_bakiye_listesiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fn_stok_bakiye_listesiResponse", Namespace="http://tempuri.org/", Order=0)]
        public Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_bakiye_listesiResponseBody Body;
        
        public fn_stok_bakiye_listesiResponse() {
        }
        
        public fn_stok_bakiye_listesiResponse(Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_bakiye_listesiResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fn_stok_bakiye_listesiResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fn_stok_bakiye_listesiResult;
        
        public fn_stok_bakiye_listesiResponseBody() {
        }
        
        public fn_stok_bakiye_listesiResponseBody(string fn_stok_bakiye_listesiResult) {
            this.fn_stok_bakiye_listesiResult = fn_stok_bakiye_listesiResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fn_cari_hareketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fn_cari_hareket", Namespace="http://tempuri.org/", Order=0)]
        public Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareketRequestBody Body;
        
        public fn_cari_hareketRequest() {
        }
        
        public fn_cari_hareketRequest(Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fn_cari_hareketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string d_sifre;
        
        public fn_cari_hareketRequestBody() {
        }
        
        public fn_cari_hareketRequestBody(string d_sifre) {
            this.d_sifre = d_sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fn_cari_hareketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fn_cari_hareketResponse", Namespace="http://tempuri.org/", Order=0)]
        public Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareketResponseBody Body;
        
        public fn_cari_hareketResponse() {
        }
        
        public fn_cari_hareketResponse(Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fn_cari_hareketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fn_cari_hareketResult;
        
        public fn_cari_hareketResponseBody() {
        }
        
        public fn_cari_hareketResponseBody(string fn_cari_hareketResult) {
            this.fn_cari_hareketResult = fn_cari_hareketResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fn_cari_hareket_detayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fn_cari_hareket_detay", Namespace="http://tempuri.org/", Order=0)]
        public Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareket_detayRequestBody Body;
        
        public fn_cari_hareket_detayRequest() {
        }
        
        public fn_cari_hareket_detayRequest(Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareket_detayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fn_cari_hareket_detayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string d_siparis;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string d_sifre;
        
        public fn_cari_hareket_detayRequestBody() {
        }
        
        public fn_cari_hareket_detayRequestBody(string d_siparis, string d_sifre) {
            this.d_siparis = d_siparis;
            this.d_sifre = d_sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fn_cari_hareket_detayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fn_cari_hareket_detayResponse", Namespace="http://tempuri.org/", Order=0)]
        public Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareket_detayResponseBody Body;
        
        public fn_cari_hareket_detayResponse() {
        }
        
        public fn_cari_hareket_detayResponse(Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareket_detayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fn_cari_hareket_detayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fn_cari_hareket_detayResult;
        
        public fn_cari_hareket_detayResponseBody() {
        }
        
        public fn_cari_hareket_detayResponseBody(string fn_cari_hareket_detayResult) {
            this.fn_cari_hareket_detayResult = fn_cari_hareket_detayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fn_cari_hareket_siparis_noRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fn_cari_hareket_siparis_no", Namespace="http://tempuri.org/", Order=0)]
        public Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareket_siparis_noRequestBody Body;
        
        public fn_cari_hareket_siparis_noRequest() {
        }
        
        public fn_cari_hareket_siparis_noRequest(Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareket_siparis_noRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fn_cari_hareket_siparis_noRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string d_siparis_no;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string d_sifre;
        
        public fn_cari_hareket_siparis_noRequestBody() {
        }
        
        public fn_cari_hareket_siparis_noRequestBody(string d_siparis_no, string d_sifre) {
            this.d_siparis_no = d_siparis_no;
            this.d_sifre = d_sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fn_cari_hareket_siparis_noResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fn_cari_hareket_siparis_noResponse", Namespace="http://tempuri.org/", Order=0)]
        public Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareket_siparis_noResponseBody Body;
        
        public fn_cari_hareket_siparis_noResponse() {
        }
        
        public fn_cari_hareket_siparis_noResponse(Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareket_siparis_noResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fn_cari_hareket_siparis_noResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fn_cari_hareket_siparis_noResult;
        
        public fn_cari_hareket_siparis_noResponseBody() {
        }
        
        public fn_cari_hareket_siparis_noResponseBody(string fn_cari_hareket_siparis_noResult) {
            this.fn_cari_hareket_siparis_noResult = fn_cari_hareket_siparis_noResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fn_siparis_erp_noRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fn_siparis_erp_no", Namespace="http://tempuri.org/", Order=0)]
        public Prodma.DataAccessB2C.ozceteFiyatlar.fn_siparis_erp_noRequestBody Body;
        
        public fn_siparis_erp_noRequest() {
        }
        
        public fn_siparis_erp_noRequest(Prodma.DataAccessB2C.ozceteFiyatlar.fn_siparis_erp_noRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fn_siparis_erp_noRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int d_siparis;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string d_sifre;
        
        public fn_siparis_erp_noRequestBody() {
        }
        
        public fn_siparis_erp_noRequestBody(int d_siparis, string d_sifre) {
            this.d_siparis = d_siparis;
            this.d_sifre = d_sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fn_siparis_erp_noResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fn_siparis_erp_noResponse", Namespace="http://tempuri.org/", Order=0)]
        public Prodma.DataAccessB2C.ozceteFiyatlar.fn_siparis_erp_noResponseBody Body;
        
        public fn_siparis_erp_noResponse() {
        }
        
        public fn_siparis_erp_noResponse(Prodma.DataAccessB2C.ozceteFiyatlar.fn_siparis_erp_noResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fn_siparis_erp_noResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fn_siparis_erp_noResult;
        
        public fn_siparis_erp_noResponseBody() {
        }
        
        public fn_siparis_erp_noResponseBody(string fn_siparis_erp_noResult) {
            this.fn_siparis_erp_noResult = fn_siparis_erp_noResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fn_stok_bakiye_iptalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fn_stok_bakiye_iptal", Namespace="http://tempuri.org/", Order=0)]
        public Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_bakiye_iptalRequestBody Body;
        
        public fn_stok_bakiye_iptalRequest() {
        }
        
        public fn_stok_bakiye_iptalRequest(Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_bakiye_iptalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fn_stok_bakiye_iptalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string d_siparis_no;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string d_no;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string d_sifre;
        
        public fn_stok_bakiye_iptalRequestBody() {
        }
        
        public fn_stok_bakiye_iptalRequestBody(string d_siparis_no, string d_no, string d_sifre) {
            this.d_siparis_no = d_siparis_no;
            this.d_no = d_no;
            this.d_sifre = d_sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fn_stok_bakiye_iptalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fn_stok_bakiye_iptalResponse", Namespace="http://tempuri.org/", Order=0)]
        public Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_bakiye_iptalResponseBody Body;
        
        public fn_stok_bakiye_iptalResponse() {
        }
        
        public fn_stok_bakiye_iptalResponse(Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_bakiye_iptalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fn_stok_bakiye_iptalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fn_stok_bakiye_iptalResult;
        
        public fn_stok_bakiye_iptalResponseBody() {
        }
        
        public fn_stok_bakiye_iptalResponseBody(string fn_stok_bakiye_iptalResult) {
            this.fn_stok_bakiye_iptalResult = fn_stok_bakiye_iptalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fn_kurRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fn_kur", Namespace="http://tempuri.org/", Order=0)]
        public Prodma.DataAccessB2C.ozceteFiyatlar.fn_kurRequestBody Body;
        
        public fn_kurRequest() {
        }
        
        public fn_kurRequest(Prodma.DataAccessB2C.ozceteFiyatlar.fn_kurRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fn_kurRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string d_sifre;
        
        public fn_kurRequestBody() {
        }
        
        public fn_kurRequestBody(string d_sifre) {
            this.d_sifre = d_sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fn_kurResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fn_kurResponse", Namespace="http://tempuri.org/", Order=0)]
        public Prodma.DataAccessB2C.ozceteFiyatlar.fn_kurResponseBody Body;
        
        public fn_kurResponse() {
        }
        
        public fn_kurResponse(Prodma.DataAccessB2C.ozceteFiyatlar.fn_kurResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fn_kurResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fn_kurResult;
        
        public fn_kurResponseBody() {
        }
        
        public fn_kurResponseBody(string fn_kurResult) {
            this.fn_kurResult = fn_kurResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fn_web_sifre_olusturRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fn_web_sifre_olustur", Namespace="http://tempuri.org/", Order=0)]
        public Prodma.DataAccessB2C.ozceteFiyatlar.fn_web_sifre_olusturRequestBody Body;
        
        public fn_web_sifre_olusturRequest() {
        }
        
        public fn_web_sifre_olusturRequest(Prodma.DataAccessB2C.ozceteFiyatlar.fn_web_sifre_olusturRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fn_web_sifre_olusturRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string d_deger;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string d_sifre;
        
        public fn_web_sifre_olusturRequestBody() {
        }
        
        public fn_web_sifre_olusturRequestBody(string d_deger, string d_sifre) {
            this.d_deger = d_deger;
            this.d_sifre = d_sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fn_web_sifre_olusturResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fn_web_sifre_olusturResponse", Namespace="http://tempuri.org/", Order=0)]
        public Prodma.DataAccessB2C.ozceteFiyatlar.fn_web_sifre_olusturResponseBody Body;
        
        public fn_web_sifre_olusturResponse() {
        }
        
        public fn_web_sifre_olusturResponse(Prodma.DataAccessB2C.ozceteFiyatlar.fn_web_sifre_olusturResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fn_web_sifre_olusturResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fn_web_sifre_olusturResult;
        
        public fn_web_sifre_olusturResponseBody() {
        }
        
        public fn_web_sifre_olusturResponseBody(string fn_web_sifre_olusturResult) {
            this.fn_web_sifre_olusturResult = fn_web_sifre_olusturResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OzceteParcaSatisSoapChannel : Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OzceteParcaSatisSoapClient : System.ServiceModel.ClientBase<Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap>, Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap {
        
        public OzceteParcaSatisSoapClient() {
        }
        
        public OzceteParcaSatisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OzceteParcaSatisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OzceteParcaSatisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OzceteParcaSatisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prodma.DataAccessB2C.ozceteFiyatlar.fn_siparis_olusturResponse Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap.fn_siparis_olustur(Prodma.DataAccessB2C.ozceteFiyatlar.fn_siparis_olusturRequest request) {
            return base.Channel.fn_siparis_olustur(request);
        }
        
        public string fn_siparis_olustur(Prodma.DataAccessB2C.ozceteFiyatlar.ArrayOfErp_siparis list, string d_sifre) {
            Prodma.DataAccessB2C.ozceteFiyatlar.fn_siparis_olusturRequest inValue = new Prodma.DataAccessB2C.ozceteFiyatlar.fn_siparis_olusturRequest();
            inValue.Body = new Prodma.DataAccessB2C.ozceteFiyatlar.fn_siparis_olusturRequestBody();
            inValue.Body.list = list;
            inValue.Body.d_sifre = d_sifre;
            Prodma.DataAccessB2C.ozceteFiyatlar.fn_siparis_olusturResponse retVal = ((Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap)(this)).fn_siparis_olustur(inValue);
            return retVal.Body.fn_siparis_olusturResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_listesiResponse Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap.fn_stok_listesi(Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_listesiRequest request) {
            return base.Channel.fn_stok_listesi(request);
        }
        
        public string fn_stok_listesi(string d_stok_kodu, string d_tedarikci, double d_miktar, string d_sifre) {
            Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_listesiRequest inValue = new Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_listesiRequest();
            inValue.Body = new Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_listesiRequestBody();
            inValue.Body.d_stok_kodu = d_stok_kodu;
            inValue.Body.d_tedarikci = d_tedarikci;
            inValue.Body.d_miktar = d_miktar;
            inValue.Body.d_sifre = d_sifre;
            Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_listesiResponse retVal = ((Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap)(this)).fn_stok_listesi(inValue);
            return retVal.Body.fn_stok_listesiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_kampanyali_stoklarResponse Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap.fn_stok_kampanyali_stoklar(Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_kampanyali_stoklarRequest request) {
            return base.Channel.fn_stok_kampanyali_stoklar(request);
        }
        
        public string fn_stok_kampanyali_stoklar(string d_sifre) {
            Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_kampanyali_stoklarRequest inValue = new Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_kampanyali_stoklarRequest();
            inValue.Body = new Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_kampanyali_stoklarRequestBody();
            inValue.Body.d_sifre = d_sifre;
            Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_kampanyali_stoklarResponse retVal = ((Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap)(this)).fn_stok_kampanyali_stoklar(inValue);
            return retVal.Body.fn_stok_kampanyali_stoklarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_durumuResponse Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap.fn_stok_durumu(Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_durumuRequest request) {
            return base.Channel.fn_stok_durumu(request);
        }
        
        public string fn_stok_durumu(string d_stok_kodu, string d_tedarikci, string d_sifre) {
            Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_durumuRequest inValue = new Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_durumuRequest();
            inValue.Body = new Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_durumuRequestBody();
            inValue.Body.d_stok_kodu = d_stok_kodu;
            inValue.Body.d_tedarikci = d_tedarikci;
            inValue.Body.d_sifre = d_sifre;
            Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_durumuResponse retVal = ((Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap)(this)).fn_stok_durumu(inValue);
            return retVal.Body.fn_stok_durumuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_bakiye_listesiResponse Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap.fn_stok_bakiye_listesi(Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_bakiye_listesiRequest request) {
            return base.Channel.fn_stok_bakiye_listesi(request);
        }
        
        public string fn_stok_bakiye_listesi(string d_sifre) {
            Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_bakiye_listesiRequest inValue = new Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_bakiye_listesiRequest();
            inValue.Body = new Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_bakiye_listesiRequestBody();
            inValue.Body.d_sifre = d_sifre;
            Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_bakiye_listesiResponse retVal = ((Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap)(this)).fn_stok_bakiye_listesi(inValue);
            return retVal.Body.fn_stok_bakiye_listesiResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareketResponse Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap.fn_cari_hareket(Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareketRequest request) {
            return base.Channel.fn_cari_hareket(request);
        }
        
        public string fn_cari_hareket(string d_sifre) {
            Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareketRequest inValue = new Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareketRequest();
            inValue.Body = new Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareketRequestBody();
            inValue.Body.d_sifre = d_sifre;
            Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareketResponse retVal = ((Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap)(this)).fn_cari_hareket(inValue);
            return retVal.Body.fn_cari_hareketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareket_detayResponse Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap.fn_cari_hareket_detay(Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareket_detayRequest request) {
            return base.Channel.fn_cari_hareket_detay(request);
        }
        
        public string fn_cari_hareket_detay(string d_siparis, string d_sifre) {
            Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareket_detayRequest inValue = new Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareket_detayRequest();
            inValue.Body = new Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareket_detayRequestBody();
            inValue.Body.d_siparis = d_siparis;
            inValue.Body.d_sifre = d_sifre;
            Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareket_detayResponse retVal = ((Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap)(this)).fn_cari_hareket_detay(inValue);
            return retVal.Body.fn_cari_hareket_detayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareket_siparis_noResponse Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap.fn_cari_hareket_siparis_no(Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareket_siparis_noRequest request) {
            return base.Channel.fn_cari_hareket_siparis_no(request);
        }
        
        public string fn_cari_hareket_siparis_no(string d_siparis_no, string d_sifre) {
            Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareket_siparis_noRequest inValue = new Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareket_siparis_noRequest();
            inValue.Body = new Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareket_siparis_noRequestBody();
            inValue.Body.d_siparis_no = d_siparis_no;
            inValue.Body.d_sifre = d_sifre;
            Prodma.DataAccessB2C.ozceteFiyatlar.fn_cari_hareket_siparis_noResponse retVal = ((Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap)(this)).fn_cari_hareket_siparis_no(inValue);
            return retVal.Body.fn_cari_hareket_siparis_noResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prodma.DataAccessB2C.ozceteFiyatlar.fn_siparis_erp_noResponse Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap.fn_siparis_erp_no(Prodma.DataAccessB2C.ozceteFiyatlar.fn_siparis_erp_noRequest request) {
            return base.Channel.fn_siparis_erp_no(request);
        }
        
        public string fn_siparis_erp_no(int d_siparis, string d_sifre) {
            Prodma.DataAccessB2C.ozceteFiyatlar.fn_siparis_erp_noRequest inValue = new Prodma.DataAccessB2C.ozceteFiyatlar.fn_siparis_erp_noRequest();
            inValue.Body = new Prodma.DataAccessB2C.ozceteFiyatlar.fn_siparis_erp_noRequestBody();
            inValue.Body.d_siparis = d_siparis;
            inValue.Body.d_sifre = d_sifre;
            Prodma.DataAccessB2C.ozceteFiyatlar.fn_siparis_erp_noResponse retVal = ((Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap)(this)).fn_siparis_erp_no(inValue);
            return retVal.Body.fn_siparis_erp_noResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_bakiye_iptalResponse Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap.fn_stok_bakiye_iptal(Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_bakiye_iptalRequest request) {
            return base.Channel.fn_stok_bakiye_iptal(request);
        }
        
        public string fn_stok_bakiye_iptal(string d_siparis_no, string d_no, string d_sifre) {
            Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_bakiye_iptalRequest inValue = new Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_bakiye_iptalRequest();
            inValue.Body = new Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_bakiye_iptalRequestBody();
            inValue.Body.d_siparis_no = d_siparis_no;
            inValue.Body.d_no = d_no;
            inValue.Body.d_sifre = d_sifre;
            Prodma.DataAccessB2C.ozceteFiyatlar.fn_stok_bakiye_iptalResponse retVal = ((Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap)(this)).fn_stok_bakiye_iptal(inValue);
            return retVal.Body.fn_stok_bakiye_iptalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prodma.DataAccessB2C.ozceteFiyatlar.fn_kurResponse Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap.fn_kur(Prodma.DataAccessB2C.ozceteFiyatlar.fn_kurRequest request) {
            return base.Channel.fn_kur(request);
        }
        
        public string fn_kur(string d_sifre) {
            Prodma.DataAccessB2C.ozceteFiyatlar.fn_kurRequest inValue = new Prodma.DataAccessB2C.ozceteFiyatlar.fn_kurRequest();
            inValue.Body = new Prodma.DataAccessB2C.ozceteFiyatlar.fn_kurRequestBody();
            inValue.Body.d_sifre = d_sifre;
            Prodma.DataAccessB2C.ozceteFiyatlar.fn_kurResponse retVal = ((Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap)(this)).fn_kur(inValue);
            return retVal.Body.fn_kurResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Prodma.DataAccessB2C.ozceteFiyatlar.fn_web_sifre_olusturResponse Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap.fn_web_sifre_olustur(Prodma.DataAccessB2C.ozceteFiyatlar.fn_web_sifre_olusturRequest request) {
            return base.Channel.fn_web_sifre_olustur(request);
        }
        
        public string fn_web_sifre_olustur(string d_deger, string d_sifre) {
            Prodma.DataAccessB2C.ozceteFiyatlar.fn_web_sifre_olusturRequest inValue = new Prodma.DataAccessB2C.ozceteFiyatlar.fn_web_sifre_olusturRequest();
            inValue.Body = new Prodma.DataAccessB2C.ozceteFiyatlar.fn_web_sifre_olusturRequestBody();
            inValue.Body.d_deger = d_deger;
            inValue.Body.d_sifre = d_sifre;
            Prodma.DataAccessB2C.ozceteFiyatlar.fn_web_sifre_olusturResponse retVal = ((Prodma.DataAccessB2C.ozceteFiyatlar.OzceteParcaSatisSoap)(this)).fn_web_sifre_olustur(inValue);
            return retVal.Body.fn_web_sifre_olusturResult;
        }
    }
}
